// <auto-generated />
using System;
using IGMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IGMS.Infrastructure.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260416020504_AddGovernanceModules")]
    partial class AddGovernanceModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IGMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("IGMS.Domain.Entities.GovernanceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Kpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Kpis");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Module");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "READ",
                            Code = "USERS.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض المستخدمين",
                            DescriptionEn = "View Users",
                            IsDeleted = false,
                            Module = "USERS"
                        },
                        new
                        {
                            Id = 2,
                            Action = "CREATE",
                            Code = "USERS.CREATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إنشاء مستخدم",
                            DescriptionEn = "Create User",
                            IsDeleted = false,
                            Module = "USERS"
                        },
                        new
                        {
                            Id = 3,
                            Action = "UPDATE",
                            Code = "USERS.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل مستخدم",
                            DescriptionEn = "Update User",
                            IsDeleted = false,
                            Module = "USERS"
                        },
                        new
                        {
                            Id = 4,
                            Action = "DELETE",
                            Code = "USERS.DELETE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "حذف مستخدم",
                            DescriptionEn = "Delete User",
                            IsDeleted = false,
                            Module = "USERS"
                        },
                        new
                        {
                            Id = 5,
                            Action = "MANAGE",
                            Code = "USERS.MANAGE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إدارة كاملة للمستخدمين",
                            DescriptionEn = "Full User Management",
                            IsDeleted = false,
                            Module = "USERS"
                        },
                        new
                        {
                            Id = 6,
                            Action = "READ",
                            Code = "DEPARTMENTS.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض الأقسام",
                            DescriptionEn = "View Departments",
                            IsDeleted = false,
                            Module = "DEPARTMENTS"
                        },
                        new
                        {
                            Id = 7,
                            Action = "CREATE",
                            Code = "DEPARTMENTS.CREATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إنشاء قسم",
                            DescriptionEn = "Create Department",
                            IsDeleted = false,
                            Module = "DEPARTMENTS"
                        },
                        new
                        {
                            Id = 8,
                            Action = "UPDATE",
                            Code = "DEPARTMENTS.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل قسم",
                            DescriptionEn = "Update Department",
                            IsDeleted = false,
                            Module = "DEPARTMENTS"
                        },
                        new
                        {
                            Id = 9,
                            Action = "DELETE",
                            Code = "DEPARTMENTS.DELETE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "حذف قسم",
                            DescriptionEn = "Delete Department",
                            IsDeleted = false,
                            Module = "DEPARTMENTS"
                        },
                        new
                        {
                            Id = 10,
                            Action = "READ",
                            Code = "RACI.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض مصفوفة RACI",
                            DescriptionEn = "View RACI Matrix",
                            IsDeleted = false,
                            Module = "RACI"
                        },
                        new
                        {
                            Id = 11,
                            Action = "CREATE",
                            Code = "RACI.CREATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إنشاء RACI",
                            DescriptionEn = "Create RACI",
                            IsDeleted = false,
                            Module = "RACI"
                        },
                        new
                        {
                            Id = 12,
                            Action = "UPDATE",
                            Code = "RACI.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل RACI",
                            DescriptionEn = "Update RACI",
                            IsDeleted = false,
                            Module = "RACI"
                        },
                        new
                        {
                            Id = 13,
                            Action = "DELETE",
                            Code = "RACI.DELETE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "حذف RACI",
                            DescriptionEn = "Delete RACI",
                            IsDeleted = false,
                            Module = "RACI"
                        },
                        new
                        {
                            Id = 14,
                            Action = "APPROVE",
                            Code = "RACI.APPROVE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "اعتماد RACI",
                            DescriptionEn = "Approve RACI",
                            IsDeleted = false,
                            Module = "RACI"
                        },
                        new
                        {
                            Id = 15,
                            Action = "READ",
                            Code = "POLICIES.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض السياسات",
                            DescriptionEn = "View Policies",
                            IsDeleted = false,
                            Module = "POLICIES"
                        },
                        new
                        {
                            Id = 16,
                            Action = "CREATE",
                            Code = "POLICIES.CREATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إنشاء سياسة",
                            DescriptionEn = "Create Policy",
                            IsDeleted = false,
                            Module = "POLICIES"
                        },
                        new
                        {
                            Id = 17,
                            Action = "UPDATE",
                            Code = "POLICIES.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل سياسة",
                            DescriptionEn = "Update Policy",
                            IsDeleted = false,
                            Module = "POLICIES"
                        },
                        new
                        {
                            Id = 18,
                            Action = "DELETE",
                            Code = "POLICIES.DELETE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "حذف سياسة",
                            DescriptionEn = "Delete Policy",
                            IsDeleted = false,
                            Module = "POLICIES"
                        },
                        new
                        {
                            Id = 19,
                            Action = "APPROVE",
                            Code = "POLICIES.APPROVE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "اعتماد سياسة",
                            DescriptionEn = "Approve Policy",
                            IsDeleted = false,
                            Module = "POLICIES"
                        },
                        new
                        {
                            Id = 20,
                            Action = "PUBLISH",
                            Code = "POLICIES.PUBLISH",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "نشر سياسة",
                            DescriptionEn = "Publish Policy",
                            IsDeleted = false,
                            Module = "POLICIES"
                        },
                        new
                        {
                            Id = 21,
                            Action = "READ",
                            Code = "TASKS.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض المهام",
                            DescriptionEn = "View Tasks",
                            IsDeleted = false,
                            Module = "TASKS"
                        },
                        new
                        {
                            Id = 22,
                            Action = "CREATE",
                            Code = "TASKS.CREATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إنشاء مهمة",
                            DescriptionEn = "Create Task",
                            IsDeleted = false,
                            Module = "TASKS"
                        },
                        new
                        {
                            Id = 23,
                            Action = "UPDATE",
                            Code = "TASKS.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل مهمة",
                            DescriptionEn = "Update Task",
                            IsDeleted = false,
                            Module = "TASKS"
                        },
                        new
                        {
                            Id = 24,
                            Action = "DELETE",
                            Code = "TASKS.DELETE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "حذف مهمة",
                            DescriptionEn = "Delete Task",
                            IsDeleted = false,
                            Module = "TASKS"
                        },
                        new
                        {
                            Id = 25,
                            Action = "ASSIGN",
                            Code = "TASKS.ASSIGN",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إسناد مهمة",
                            DescriptionEn = "Assign Task",
                            IsDeleted = false,
                            Module = "TASKS"
                        },
                        new
                        {
                            Id = 26,
                            Action = "READ",
                            Code = "KPI.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض مؤشرات الأداء",
                            DescriptionEn = "View KPIs",
                            IsDeleted = false,
                            Module = "KPI"
                        },
                        new
                        {
                            Id = 27,
                            Action = "CREATE",
                            Code = "KPI.CREATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إنشاء مؤشر أداء",
                            DescriptionEn = "Create KPI",
                            IsDeleted = false,
                            Module = "KPI"
                        },
                        new
                        {
                            Id = 28,
                            Action = "UPDATE",
                            Code = "KPI.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل مؤشر أداء",
                            DescriptionEn = "Update KPI",
                            IsDeleted = false,
                            Module = "KPI"
                        },
                        new
                        {
                            Id = 29,
                            Action = "DELETE",
                            Code = "KPI.DELETE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "حذف مؤشر أداء",
                            DescriptionEn = "Delete KPI",
                            IsDeleted = false,
                            Module = "KPI"
                        },
                        new
                        {
                            Id = 30,
                            Action = "READ",
                            Code = "RISKS.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض المخاطر",
                            DescriptionEn = "View Risks",
                            IsDeleted = false,
                            Module = "RISKS"
                        },
                        new
                        {
                            Id = 31,
                            Action = "CREATE",
                            Code = "RISKS.CREATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "إنشاء مخاطرة",
                            DescriptionEn = "Create Risk",
                            IsDeleted = false,
                            Module = "RISKS"
                        },
                        new
                        {
                            Id = 32,
                            Action = "UPDATE",
                            Code = "RISKS.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل مخاطرة",
                            DescriptionEn = "Update Risk",
                            IsDeleted = false,
                            Module = "RISKS"
                        },
                        new
                        {
                            Id = 33,
                            Action = "DELETE",
                            Code = "RISKS.DELETE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "حذف مخاطرة",
                            DescriptionEn = "Delete Risk",
                            IsDeleted = false,
                            Module = "RISKS"
                        },
                        new
                        {
                            Id = 34,
                            Action = "READ",
                            Code = "REPORTS.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض التقارير",
                            DescriptionEn = "View Reports",
                            IsDeleted = false,
                            Module = "REPORTS"
                        },
                        new
                        {
                            Id = 35,
                            Action = "EXPORT",
                            Code = "REPORTS.EXPORT",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تصدير التقارير",
                            DescriptionEn = "Export Reports",
                            IsDeleted = false,
                            Module = "REPORTS"
                        },
                        new
                        {
                            Id = 36,
                            Action = "READ",
                            Code = "SETTINGS.READ",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "عرض الإعدادات",
                            DescriptionEn = "View Settings",
                            IsDeleted = false,
                            Module = "SETTINGS"
                        },
                        new
                        {
                            Id = 37,
                            Action = "UPDATE",
                            Code = "SETTINGS.UPDATE",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionAr = "تعديل الإعدادات",
                            DescriptionEn = "Update Settings",
                            IsDeleted = false,
                            Module = "SETTINGS"
                        });
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountableUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RaciMatrixId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountableUserId");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("RaciMatrixId");

                    b.ToTable("RaciActivities", (string)null);
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.ToTable("RaciMatrices", (string)null);
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciParticipant", b =>
                {
                    b.Property<int>("RaciActivityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("RaciActivityId", "UserId", "Role");

                    b.HasIndex("UserId");

                    b.HasIndex("RaciActivityId", "Role");

                    b.ToTable("RaciParticipants", (string)null);
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Likelihood")
                        .HasColumnType("int");

                    b.Property<string>("MitigationPlanAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            NameAr = "مدير النظام",
                            NameEn = "System Admin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MANAGER",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            NameAr = "مدير",
                            NameEn = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Code = "USER",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            NameAr = "مستخدم",
                            NameEn = "User"
                        },
                        new
                        {
                            Id = 4,
                            Code = "VIEWER",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemRole = true,
                            NameAr = "مشاهد",
                            NameEn = "Viewer"
                        });
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 25,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 26,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 27,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 28,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 29,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 31,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 32,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 33,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 34,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 35,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 36,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 37,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 24,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 26,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 27,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 29,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 31,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 32,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 33,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 34,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 35,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 36,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 21,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 22,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 23,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 26,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 34,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 36,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 6,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 15,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 21,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 26,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 34,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 36,
                            GrantedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedBy = "System"
                        });
                });

            modelBuilder.Entity("IGMS.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmiratesId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UaePassSub")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdObjectId")
                        .IsUnique()
                        .HasFilter("[AdObjectId] IS NOT NULL");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmiratesId")
                        .IsUnique()
                        .HasFilter("[EmiratesId] IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UaePassSub")
                        .IsUnique()
                        .HasFilter("[UaePassSub] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "admin@igms.local",
                            FullNameAr = "مدير النظام",
                            FullNameEn = "System Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$niIs4o4GkL0iayBWHKCqGODzgpP8QveK9O8EG6lZO6M9WbNNCOxyy",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("IGMS.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssignedBy = "System"
                        });
                });

            modelBuilder.Entity("IGMS.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.UserProfile", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Department", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.UserProfile", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IGMS.Domain.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.GovernanceTask", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.UserProfile", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("IGMS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Kpi", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("IGMS.Domain.Entities.UserProfile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Department");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Policy", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("IGMS.Domain.Entities.UserProfile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Department");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciActivity", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.UserProfile", "AccountableUser")
                        .WithMany()
                        .HasForeignKey("AccountableUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IGMS.Domain.Entities.RaciMatrix", "Matrix")
                        .WithMany("Activities")
                        .HasForeignKey("RaciMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountableUser");

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciMatrix", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.UserProfile", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IGMS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciParticipant", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.RaciActivity", "Activity")
                        .WithMany("Participants")
                        .HasForeignKey("RaciActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IGMS.Domain.Entities.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Risk", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("IGMS.Domain.Entities.UserProfile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Department");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IGMS.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.Department", "Department")
                        .WithMany("Members")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("IGMS.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IGMS.Domain.Entities.UserProfile", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciActivity", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.RaciMatrix", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IGMS.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
